Repository prgrms-fe-devcourse/NFE1-1-3-techLog, pull requests merged in 2024-10, with the labels that each got.

#39 [BE] feature : 게시물 수정 구현
  BackEnd/controllers/updateController.js
  BackEnd/routes/updateRoutes.js
Labels: Feature🍀

#42 [BE] fix : Router및 불필요한 파일 삭제
  BackEnd/app.js
  BackEnd/models/read.js
  BackEnd/models/readAll.js
  BackEnd/routes/deleteRoutes.js
  BackEnd/routes/postRoutes.js
  BackEnd/routes/readAllRoutes.js
  BackEnd/routes/readRoutes.js
  BackEnd/routes/updateRoutes.js
Labels: 🔧Rrefactoring

#47 [FE] 모달 컴포넌트 구현 및 커스텀 훅 분리
  frontend/src/App.tsx
  frontend/src/components/Button/DuplicateButton/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Modal/CategorySelect/index.tsx
  frontend/src/components/Modal/ModalForm.tsx
  frontend/src/components/Modal/ModalRead.tsx
  frontend/src/components/Modal/index.styles.ts
  frontend/src/components/Modal/index.tsx
  frontend/src/hooks/useDialog.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/hooks/useModal.ts
  frontend/src/interface/category.ts
  frontend/src/interface/modalProps.ts
  frontend/src/pages/login/index.tsx
  frontend/src/pages/main/index.tsx
  frontend/src/pages/signup/index.styles.ts
  frontend/src/pages/signup/index.tsx
Labels: Feature🍀, 🌟HTML&CSS

#51 [FE] 로그인 기능 구현 및 초기 설정
  frontend/src/api/auth.ts
  frontend/src/api/config.ts
  frontend/src/api/index.ts
  frontend/src/components/Button/AuthButton/index.tsx
  frontend/src/components/Layout/Sidebar/index.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/login/index.styles.ts
  frontend/src/pages/login/index.tsx
Labels: Feature🍀

#54 [BE] fix: 토큰, 쿠키 만료시간 3분으로 수정, 각 상태 코드에 따른 errorCode 추가
  BackEnd/controllers/users/idCheckController.js
  BackEnd/controllers/users/loginController.js
  BackEnd/controllers/users/signupController.js
  BackEnd/controllers/users/validators.js
  BackEnd/middleware/auth.js
Labels: 👹BugFix
