Repository prgrms-fe-devcourse/NFE1-1-3-techLog, pull requests merged in 2024-11, with the labels that each got.

#71 [FE] 질문지 단일조회,수정,삭제 기능 구현
  frontend/src/api/index.ts
  frontend/src/api/questionAnswer.ts
  frontend/src/components/Dialog/index.styles.ts
  frontend/src/components/ItemBox/index.tsx
  frontend/src/components/Layout/Sidebar/index.tsx
  frontend/src/components/Modal/ModalForm.tsx
  frontend/src/components/Modal/ModalRead.tsx
  frontend/src/constants/querykeys.ts
  frontend/src/hooks/useDialog.ts
  frontend/src/hooks/useModal.ts
  frontend/src/interface/modalProps.ts
  frontend/src/interface/qaData.ts
  frontend/src/pages/main/index.tsx
  frontend/src/store/idxStore.ts
  frontend/src/store/modalStore.ts
Labels: Feature🍀

#77 [BE] 웹소켓 세팅
  BackEnd/app.js
  BackEnd/controllers/comments/commentController.js
  BackEnd/models/comment.js
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/routes/commentRoutes.js
  BackEnd/server.js
  BackEnd/websocket/websocketServer.js
Labels: Feature🍀

#75 [FE] 카테고리별 조회 기능 구현
  frontend/src/pages/main/index.tsx
Labels: Feature🍀

#81 [FE] feature : 회원가입 기능 구현
  frontend/src/api/auth.ts
  frontend/src/api/config.ts
  frontend/src/components/Button/SignButton/index.tsx
  frontend/src/hooks/useSignup.ts
  frontend/src/pages/signup/index.styles.ts
  frontend/src/pages/signup/index.tsx
Labels: Feature🍀

#83 [FE] style : 텍스트 크기 변경
  .prettierrc
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/config.ts
  frontend/src/api/index.ts
  frontend/src/components/Button/AuthButton/index.tsx
  frontend/src/components/Button/DuplicateButton/index.tsx
  frontend/src/components/Dialog/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/ItemBox/index.styles.ts
  frontend/src/components/ItemBox/index.tsx
  frontend/src/components/Modal/CategorySelect/index.tsx
  frontend/src/components/Modal/ModalForm.tsx
  frontend/src/components/Modal/ModalRead.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/constants/path.ts
  frontend/src/constants/querykeys.ts
  frontend/src/hooks/useDialog.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/hooks/useModal.ts
  frontend/src/index.tsx
  frontend/src/pages/main/index.tsx
  frontend/src/pages/signup/index.tsx
  frontend/src/store/idxStore.ts
  frontend/src/store/modalStore.ts
Labels: 🌟HTML&CSS, 👹BugFix

#90 [BE] 회원가입 API 기능 구현
  frontend/src/api/auth.ts
  frontend/src/api/config.ts
  frontend/src/components/Button/AuthButton/index.tsx
  frontend/src/pages/signup/index.tsx
Labels: Feature🍀

#80 [BE] Feat: ws 에서 socket.io로 변경하여 웹소켓 구현
  BackEnd/app.js
  BackEnd/controllers/comments/commentController.js
  BackEnd/models/comment.js
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/routes/commentRoutes.js
  BackEnd/server.js
  BackEnd/websocket/websocketServer.js
Labels: Feature🍀

#92 [FE] add : 암기카드 flip시 테두리 효과
  frontend/.eslintrc.json
  frontend/src/components/Button/DuplicateButton/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/ItemBox/index.styles.ts
  frontend/src/components/ItemBox/index.tsx
  frontend/src/constants/querykeys.ts
  frontend/src/hooks/useDialog.ts
  frontend/src/hooks/useLogin.ts
Labels: 🌟HTML&CSS

#97 Fix: string 타입으로 ID를 전송해도 정상적으로 작동
  BackEnd/websocket/websocketServer.js
Labels: 👹BugFix

#98 [FE] - fix: 사이드바 고정, 글쓰기 버튼 z-index 수정
  frontend/src/components/Layout/MainLayout.tsx
  frontend/src/components/Layout/Sidebar/index.styles.ts
  frontend/src/pages/main/index.styles.ts
Labels: 🌟HTML&CSS

#100 [BE] FIX : socket.io 댓글 불러오기 로직 변경
  BackEnd/models/comment.js
  BackEnd/server.js
  BackEnd/websocket/websocketServer.js
Labels: 👹BugFix

#101 [FE] socketio 웹소켓 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Comment/index.styles.ts
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Input/CommentInput.tsx
  frontend/src/components/Modal/ModalForm.tsx
  frontend/src/components/Modal/ModalRead.tsx
  frontend/src/components/Modal/index.styles.ts
  frontend/src/hooks/useSignup.ts
Labels: Feature🍀

#91 [COMMON] - feature: README.md 작성
  README.md
Labels: 🌐Setting

#104 [FE] 댓글 기능 수정
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Input/CommentInput.tsx
  frontend/src/components/Modal/ModalRead.tsx
Labels: Feature🍀

#109 [FE] 마이페이지 UI 수정
  frontend/src/pages/main/index.styles.ts
  frontend/src/pages/main/index.tsx
  frontend/src/pages/mypage/index.tsx
Labels: Feature🍀
